[
    { "id": 1, "name": "Super Strength", "description": "Ability to lift and exert immense physical force." },
    { "id": 2, "name": "Flight", "description": "Power to soar through the skies unaided." },
    { "id": 3, "name": "Invisibility", "description": "Ability to become unseen at will." },
    { "id": 4, "name": "Telepathy", "description": "Read and communicate through thoughts." },
    { "id": 5, "name": "Telekinesis", "description": "Move objects with the power of the mind." },
    { "id": 6, "name": "Super Speed", "description": "Move at extraordinary velocities." },
    { "id": 7, "name": "Time Manipulation", "description": "Slow down, stop, or rewind time." },
    { "id": 8, "name": "Shape-shifting", "description": "Transform appearance or body into other forms." },
    { "id": 9, "name": "Healing Factor", "description": "Recover rapidly from wounds and injuries." },
    { "id": 10, "name": "Immortality", "description": "Cannot die of age or natural causes." },
    { "id": 11, "name": "Invulnerability", "description": "Resistance to all forms of harm." },
    { "id": 12, "name": "X-Ray Vision", "description": "See through solid objects." },
    { "id": 13, "name": "Precognition", "description": "Foresee future events." },
    { "id": 14, "name": "Mind Control", "description": "Command and influence others’ actions." },
    { "id": 15, "name": "Super Intelligence", "description": "Enhanced mental capacity and learning speed." },
    { "id": 16, "name": "Animal Communication", "description": "Understand and talk to animals." },
    { "id": 17, "name": "Underwater Breathing", "description": "Breathe freely beneath water." },
    { "id": 18, "name": "Wall-Crawling", "description": "Cling to and scale vertical surfaces." },
    { "id": 19, "name": "Night Vision", "description": "See clearly in complete darkness." },
    { "id": 20, "name": "Super Hearing", "description": "Detect sounds across vast distances." },
    { "id": 21, "name": "Energy Projection", "description": "Emit blasts of raw energy." },
    { "id": 22, "name": "Force Fields", "description": "Generate protective energy barriers." },
    { "id": 23, "name": "Elasticity", "description": "Stretch and reshape the body." },
    { "id": 24, "name": "Size Shifting", "description": "Increase or decrease physical size." },
    { "id": 25, "name": "Density Control", "description": "Alter density to phase or harden body." },
    { "id": 26, "name": "Elemental Control: Fire", "description": "Manipulate and generate flames." },
    { "id": 27, "name": "Elemental Control: Water", "description": "Manipulate and shape water." },
    { "id": 28, "name": "Elemental Control: Earth", "description": "Control rocks, soil, and minerals." },
    { "id": 29, "name": "Elemental Control: Air", "description": "Manipulate wind and currents." },
    { "id": 30, "name": "Weather Control", "description": "Summon storms, rain, or lightning." },
    { "id": 31, "name": "Magnetism Control", "description": "Manipulate magnetic fields and metals." },
    { "id": 32, "name": "Plant Manipulation", "description": "Control, grow, and animate plants." },
    { "id": 33, "name": "Ice Manipulation", "description": "Generate and shape ice." },
    { "id": 34, "name": "Electricity Control", "description": "Harness and project electricity." },
    { "id": 35, "name": "Gravity Control", "description": "Manipulate gravitational forces." },
    { "id": 36, "name": "Portal Creation", "description": "Open gateways between locations." },
    { "id": 37, "name": "Teleportation", "description": "Instantly move from one place to another." },
    { "id": 38, "name": "Clairvoyance", "description": "See distant places and events." },
    { "id": 39, "name": "Illusion Casting", "description": "Project convincing false images." },
    { "id": 40, "name": "Sound Manipulation", "description": "Control and generate sound waves." },
    { "id": 41, "name": "Light Manipulation", "description": "Bend or emit light." },
    { "id": 42, "name": "Shadow Manipulation", "description": "Control and solidify shadows." },
    { "id": 43, "name": "Probability Manipulation", "description": "Alter odds of events occurring." },
    { "id": 44, "name": "Luck", "description": "Fortune always favors the user." },
    { "id": 45, "name": "Enhanced Agility", "description": "Perform incredible acrobatics." },
    { "id": 46, "name": "Enhanced Reflexes", "description": "React with superhuman speed." },
    { "id": 47, "name": "Super Stamina", "description": "Resist fatigue for extended periods." },
    { "id": 48, "name": "Regeneration", "description": "Rebuild damaged body parts." },
    { "id": 49, "name": "Shapeshift: Animal", "description": "Transform into animals." },
    { "id": 50, "name": "Shapeshift: Object", "description": "Transform into inanimate items." },
    { "id": 51, "name": "Mind Reading", "description": "Hear the thoughts of others." },
    { "id": 52, "name": "Astral Projection", "description": "Separate spirit from body." },
    { "id": 53, "name": "Duplication", "description": "Create identical copies of oneself." },
    { "id": 54, "name": "Mimicry", "description": "Copy abilities of others." },
    { "id": 55, "name": "Power Nullification", "description": "Cancel out others’ powers." },
    { "id": 56, "name": "Power Amplification", "description": "Boost abilities beyond their limits." },
    { "id": 57, "name": "Language Mastery", "description": "Understand and speak all tongues." },
    { "id": 58, "name": "Super Vision", "description": "See microscopic or telescopic distances." },
    { "id": 59, "name": "Bulletproof Skin", "description": "Flesh impervious to bullets." },
    { "id": 60, "name": "Sonic Scream", "description": "Emit destructive sound waves." },
    { "id": 61, "name": "Geokinesis", "description": "Shape mountains and terrain." },
    { "id": 62, "name": "Hydrokinesis", "description": "Command oceans and rivers." },
    { "id": 63, "name": "Pyrokinesis", "description": "Ignite fires with the mind." },
    { "id": 64, "name": "Cryokinesis", "description": "Freeze environments instantly." },
    { "id": 65, "name": "Electrokinesis", "description": "Summon lightning at will." },
    { "id": 66, "name": "Technopathy", "description": "Control and communicate with machines." },
    { "id": 67, "name": "Radiation Control", "description": "Emit and absorb radiation safely." },
    { "id": 68, "name": "Toxin Immunity", "description": "Unaffected by poisons or disease." },
    { "id": 69, "name": "Camouflage", "description": "Blend seamlessly into surroundings." },
    { "id": 70, "name": "Echolocation", "description": "Navigate via reflected sound waves." },
    { "id": 71, "name": "Hyper Awareness", "description": "Heightened senses and perception." },
    { "id": 72, "name": "Enhanced Smell", "description": "Detect scents across long distances." },
    { "id": 73, "name": "Enhanced Taste", "description": "Identify substances instantly by flavor." },
    { "id": 74, "name": "Enhanced Touch", "description": "Feel even the slightest vibrations." },
    { "id": 75, "name": "Enhanced Balance", "description": "Never lose footing or coordination." },
    { "id": 76, "name": "Psychometry", "description": "Read history of objects by touch." },
    { "id": 77, "name": "Dream Walking", "description": "Enter and influence dreams." },
    { "id": 78, "name": "Energy Absorption", "description": "Take in energy to fuel powers." },
    { "id": 79, "name": "Energy Conversion", "description": "Change one type of energy to another." },
    { "id": 80, "name": "Self-Sustenance", "description": "Survive without food, water, or sleep." },
    { "id": 81, "name": "Longevity", "description": "Greatly extended lifespan." },
    { "id": 82, "name": "Shapeshift: Gender", "description": "Change biological sex at will." },
    { "id": 83, "name": "Shapeshift: Age", "description": "Appear older or younger instantly." },
    { "id": 84, "name": "Shapeshift: Voice", "description": "Imitate any vocal sound perfectly." },
    { "id": 85, "name": "Weapon Summoning", "description": "Manifest weapons out of thin air." },
    { "id": 86, "name": "Weapon Mastery", "description": "Unmatched skill with all weapons." },
    { "id": 87, "name": "Martial Mastery", "description": "Perfect command of combat styles." },
    { "id": 88, "name": "Enhanced Jumping", "description": "Leap across massive distances." },
    { "id": 89, "name": "Gliding", "description": "Drift through the air gracefully." },
    { "id": 90, "name": "Bone Manipulation", "description": "Control and weaponize skeletal structure." },
    { "id": 91, "name": "Blood Manipulation", "description": "Command and solidify blood." },
    { "id": 92, "name": "Sand Manipulation", "description": "Shape and control sandstorms." },
    { "id": 93, "name": "Crystal Manipulation", "description": "Grow and control crystals." },
    { "id": 94, "name": "Smoke Manipulation", "description": "Summon and control smoke." },
    { "id": 95, "name": "Acid Generation", "description": "Secrete or project corrosive acid." },
    { "id": 96, "name": "Sound Absorption", "description": "Silence all surrounding noise." },
    { "id": 97, "name": "Dream Manipulation", "description": "Control and reshape dreams." },
    { "id": 98, "name": "Dimensional Travel", "description": "Move between alternate realities." },
    { "id": 99, "name": "Cosmic Awareness", "description": "Sense the universe’s hidden truths." },
    { "id": 100, "name": "Omnilingualism", "description": "Fluently speak any language." }
  ]
  